#!/bin/bash
# Example usage scripts for Simple Whisper Application
# This file shows various ways to use the application

echo "=============================================="
echo "SIMPLE WHISPER - USAGE EXAMPLES"
echo "=============================================="

echo ""
echo "1. BASIC USAGE"
echo "--------------"
echo ""
echo "# 1.1 Record audio (press Ctrl+C to stop) and transcribe"
echo "python simple_whisper.py --record"
echo ""
echo "# 1.2 Record for 10 seconds and transcribe"
echo "python simple_whisper.py --record --duration 10"
echo ""
echo "# 1.3 Transcribe an existing audio file"
echo "python simple_whisper.py --audio recording.wav"
echo ""

echo "2. AUDIO DEVICE SELECTION"
echo "-------------------------"
echo ""
echo "# 2.1 List available audio input devices"
echo "python simple_whisper.py --list-audio-devices"
echo ""
echo "# 2.2 Record using specific microphone (device ID 5)"
echo "python simple_whisper.py --record --input-device 5"
echo ""
echo "# 2.3 Record using MacBook Pro microphone (if device ID 5)"
echo "python simple_whisper.py --record --duration 5 --input-device 5 --model tiny"
echo ""

echo "3. MODEL SELECTION"
echo "------------------"
echo ""
echo "# 3.1 Use tiny model (fastest, lowest accuracy)"
echo "python simple_whisper.py --record --model tiny"
echo ""
echo "# 3.2 Use base model (good balance)"
echo "python simple_whisper.py --record --model base"
echo ""
echo "# 3.3 Use medium model (high accuracy)"
echo "python simple_whisper.py --record --model medium"
echo ""
echo "# 3.4 Use large model (highest accuracy)"
echo "python simple_whisper.py --record --model large"
echo ""

echo "4. COMPUTATION DEVICE SELECTION"
echo "--------------------------------"
echo ""
echo "# 4.1 Force CPU usage"
echo "python simple_whisper.py --record --device cpu"
echo ""
echo "# 4.2 Use NVIDIA GPU (CUDA) if available"
echo "python simple_whisper.py --record --device cuda"
echo ""
echo "# 4.3 Use Apple Silicon GPU (MPS) if available"
echo "python simple_whisper.py --record --device mps"
echo ""

echo "5. LANGUAGE SETTINGS"
echo "--------------------"
echo ""
echo "# 5.1 Transcribe in English"
echo "python simple_whisper.py --record --language en"
echo ""
echo "# 5.2 Transcribe in Chinese"
echo "python simple_whisper.py --record --language zh"
echo ""
echo "# 5.3 Transcribe in Japanese"
echo "python simple_whisper.py --record --language ja"
echo ""

echo "6. OUTPUT FILES"
echo "---------------"
echo ""
echo "# 6.1 Specify custom audio filename"
echo "python simple_whisper.py --record --output-audio my_recording.wav"
echo ""
echo "# 6.2 Specify custom transcription filename"
echo "python simple_whisper.py --record --output-text meeting_notes.txt"
echo ""
echo "# 6.3 Specify both output files"
echo "python simple_whisper.py --record --output-audio recording.wav --output-text transcription.txt"
echo ""

echo "7. ADVANCED EXAMPLES"
echo "--------------------"
echo ""
echo "# 7.1 High-quality meeting recording"
echo "python simple_whisper.py --record --duration 600 --model medium --language en --output-text meeting.txt"
echo ""
echo "# 7.2 Transcribe interview with specific microphone"
echo "python simple_whisper.py --record --duration 1800 --model small --input-device 0 --language zh --output-text interview.txt"
echo ""
echo "# 7.3 Batch process all audio files in a folder"
echo "python batch_transcribe.py ./audio_files --model base --output-folder ./transcriptions"
echo ""
echo "# 7.4 Use interactive mode"
echo "python interactive_whisper.py"
echo ""

echo "8. TROUBLESHOOTING"
echo "------------------"
echo ""
echo "# 8.1 Test audio recording"
echo "python simple_whisper.py --record --duration 2 --model tiny"
echo ""
echo "# 8.2 Test model loading"
echo "python -c \"import whisper; model = whisper.load_model('tiny'); print(f'Model loaded on: {model.device}')\""
echo ""
echo "# 8.3 Test audio device"
echo "python -c \"import sounddevice as sd; print(f'Default input: {sd.default.device[0]}')\""
echo ""

echo "=============================================="
echo "QUICK REFERENCE"
echo "=============================================="
echo ""
echo "Common options:"
echo "  --record              Record from microphone"
echo "  --duration SECONDS    Recording duration"
echo "  --audio FILE          Transcribe existing file"
echo "  --model SIZE          Model size: tiny, base, small, medium, large"
echo "  --input-device ID     Audio input device ID"
echo "  --device TYPE         Computation device: cpu, cuda, mps"
echo "  --language CODE       Language code: en, zh, ja, etc."
echo "  --output-audio FILE   Save audio to file"
echo "  --output-text FILE    Save transcription to file"
echo ""
echo "Use --help for complete options:"
echo "python simple_whisper.py --help"
echo ""